board:
  rows: 3
  cols: 5
  number_min: 1
  number_max: 90

game:
  starting_points_per_player: 100

rewards:
  line_percent: 0.10
  bingo_percent: 0.50

penalties:
  wrong_number: -1
  false_claim: -3

modes:
  easy:
    bots: 4
  medium:
    bots: 9
  hard:
    bots: 19

